version: '3.8'

services:
  # Neo4j Database for Knowledge Graph
  neo4j:
    image: neo4j:5.12
    container_name: neo4j-hallucination
    ports:
      - "7474:7474"  # Neo4j Browser (optional)
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/1234  # Match your .env
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - mcp_crawl4ai_neo4j_data:/data
      - mcp_crawl4ai_neo4j_logs:/logs
    networks:
      - mcp_crawl4ai_network

  # MCP Crawl4AI Server
  mcp-server:
    build: .
    container_name: mcp-crawl4ai-server
    ports:
      - "8051:8051"
    env_file:
      - .env
    depends_on:
      - neo4j
    networks:
      - mcp_crawl4ai_network
    volumes:
      - ./scripts:/app/scripts  # Mount local scripts directory
      - ./reports:/app/reports  # Mount for hallucination reports
      - mcp_crawl4ai_server_cache:/app/cache  # Server cache

volumes:
  mcp_crawl4ai_neo4j_data:
    name: mcp_crawl4ai_neo4j_data
  mcp_crawl4ai_neo4j_logs:
    name: mcp_crawl4ai_neo4j_logs
  mcp_crawl4ai_server_cache:
    name: mcp_crawl4ai_server_cache

networks:
  mcp_crawl4ai_network:
    name: mcp_crawl4ai_network
    driver: bridge